### PR TITLE
Added compability with CitizensBooks.

### PR DESCRIPTION
**Pull request by nicuch**
[https://www.spigotmc.org/resources/citizensbooks.37465/](url)
Some people requested for compability between Quests and CitizensBooks, so they can open a book when the quest start/end or between stages.

### CODE REVIEW

**Comment by nicuch** [comment]
FlyingPikachu/Quests/#466

**Comment by FlyingPikachu** [comment]
Sorry for the delay in reviewing this. Everything looks tidy. Thanks for your work!

**Comment by FlyingPikachu** [comment]
@nicuch Plugin is failing to compile with the maven repo you provided. See http://ci.ac3-servers.eu/job/Quests/485/

**Comment by FlyingPikachu** [comment]
@nicuch Added the jar to Quests for the time being. If you're able to get a repository working, please let me know :)

**Pull request merged**
