### PR TITLE
! Ignore IndexOutOfBoundsExceptions when loading data

### PR DESCRIPTION
**Pull request by PikachuEXE**
Could be caused by corrupted data due to
- Exception during saving
- Manually change file content

### CODE REVIEW

**Comment by FlyingPikachu** [comment]
Wouldn't it be better to let the error print, alerting the op?

**Comment by PikachuEXE** [comment]
Yes, this is just an attempt for fixing those errors.
But I am not sure how to handle this property. (i.e. who should be notified, what message to use...)

**Comment by FlyingPikachu** [comment]
So we're not really fixing it, just making the error look better? In that case, could you post the data you used to trigger this so I can come up with a message(s)?

**Comment by PikachuEXE** [comment]
I have added some debug message logging on my own build
It would take some time to gather the data (since I have no idea if there is any corrupted data got loaded again)

**Comment by FlyingPikachu** [comment]
You don't need to go that far! Let's just leave this one be and cross the bridge later when there's a ticket.

Also - thanks for jumping in to help, repeatedly! I appreciate it! :)

**Comment by PikachuEXE** [comment]
I think any exception raised actually affects server performance.
Also makes the log messy.
And I always fix thing when I can :D

**Pull request closed without merging**
