### PR TITLE
Moved the objective title above the start message

### PR DESCRIPTION
**Pull request by christophe6**
Title has been moved to make a more clear message.

=> https://img.christophe6.be/E2qLh.png

### CODE REVIEW

**Comment by christophe6** [comment]
My IDE somehow doesn't manage to give me the tips so this is why there might be some typo's, although this was just copy paste ;).

**Comment by FlyingPikachu** [comment]
@christophe6 I approved your last PR (#396) because of the Placeholder API contribution. The fact you had switched the order of the start and objective messages seemed trivial.

Now if I'm not mistaken, you're switching them back? What is the reasoning behind this?

(Also please fix your IDE if you intend to make any more PR's - thanks)

**Comment by christophe6** [comment]
I accidentally switched the title too. The title should be above the start of the message and not between the stary message and objective message imo.

**Comment by FlyingPikachu** [comment]
Closing as unnecessary cosmetic change.

**Pull request closed without merging**
