### PR TITLE
Feature/cmd/admin/remove completed quest

### PR DESCRIPTION
**Pull request by PikachuEXE**
This is to address #66

# Changes
- New command: `/questadmin stats`
- New command: `/questadmin removecompletedquest`

# Bug
The description shown when typing `/questadmin stats` is using the `/quests stats` one due an existing bug.
This bug only happens when there is a sub-command with same name for prefix `/quests` already.

### CODE REVIEW

**Comment by Leescar** [comment]
It looks like one can only pull data from an online player?

**Comment by FlyingPikachu** [comment]
Thank you for the commit! Can you post an example of what /questadmin stats would output? I am not able to test it atm.

**Comment by PikachuEXE** [comment]
I think I found a bug.
Since I only test it with myself, I forgot the message will be sent to the player (instead of command sender).

I will fix this soon.
I will try to make it work for offline players too.

**Comment by PikachuEXE** [comment]
Bug fixed
However I found it a bit difficult to change the commands to be offline player compatible.
I can try again later after this PR is accpeted.

Here are some screenshots for running commands for the 2 new commands:

### `/questadmin stats`
stats_in_game
stats_in_console

### `/questadmin removecompletedquest`
removecompletedquest_in_game
removecompletedquest_in_console

**Comment by Leescar** [comment]
Amazing! This will make altering and debugging quests a snap

**Comment by FlyingPikachu** [comment]
Will merge now. I may change "removecompletedquests" to something shorter. Thanks again~

**Pull request merged**
