### PR TITLE
Parrots were added in 1.12 and are tameable

### PR DESCRIPTION
**Pull request by i9hdkill**
This simply adds parrots as tameable quest objectives

### CODE REVIEW

**Comment by FlyingPikachu** [comment]
@i9hdkill Thanks for your commit! I oughta make sure this is all that needs to be done. If so, I'll be happy to accept this.

**Comment by i9hdkill** [comment]
Rebased on latest version after reformatting. Yes this works, we tested this.

**Comment by i9hdkill** [comment]
Buuut it would be better to get entities and if they are tameable from bukkit directly, would that would require a lot more work.

**Comment by FlyingPikachu** [comment]
@i9hdkill I'm having trouble determining if a mob is Tameable from just the String name. Unless someone knows a way of doing this, I'll accept this commit soon.

**Comment by FlyingPikachu** [comment]
Merging this now as I am convinced there is no way to easily check if a mob is Tameable from its String name. I believe a rewrite of how this part of the plugin passes data would be necessary, but I'm open to being wrong. Thanks for your commit @i9hdkill

**Pull request merged**
