### PR TITLE
Ignore error for non module class.

### PR DESCRIPTION
**Pull request by DNx5**

### CODE REVIEW

**Comment by FlyingPikachu** [comment]
Thanks for the commit! I don't quite get why this error should be ignored, though. Please explain?

**Comment by DNx5** [comment]
I'm not good at explaining.
The plugin will check every single class in the jar module. if the class file is not child of CustomObjective, CustomRequirement, or CustomReward. It's will always print an error.
so, I make a count how many class module loaded. if the count isn't zero, it wouldn't print the error.

**Comment by FlyingPikachu** [comment]
Sorry for the (very) late response.

Isn't it better for the errors to print so that the server op (and then, the module author) can be notified of the issue?

**Comment by FlyingPikachu** [comment]
Accidental close, my bad.

**Comment by DNx5** [comment]
that's false error. non module class in the jar file should be okay.

**Pull request merged**
