### PR TITLE
Fix for #625

### PR DESCRIPTION
**Pull request by frost-byte**
When defining a new usage of a CustomObjective a copy of its Datamap is applied

### CODE REVIEW

**Comment by FlyingPikachu** [comment]
Thanks for the PR. I'm a little skeptical as to this being necessary now that the data map isn't final. If a module really needs just the keys, it should call `getData().keySet()` and continue on locally, or use a method similar to this _locally_.

**Comment by frost-byte** [comment]
Am I supposed to overwrite the CreateStagePrompt class?  Just exactly how do you see me hooking into the processing of input during the creation of a stage’s objective?

**Comment by frost-byte** [comment]
As I explained, final or not, it does not matter. Only one instance of the class is created and the Prompt pulls the same map instance either way

**Comment by FlyingPikachu** [comment]
I understand it's only one instance, but clearly I'm missing something here. I'll spend some time playing with your code in #625 and get back to you.

**Comment by FlyingPikachu** [comment]
Closed pending further discussion. See #625

**Pull request closed without merging**
