### PR TITLE
Reformatted code and added javadoc comments to particles enums.

### PR DESCRIPTION
**Pull request by GregZ123**
* Reformatted all classes for easier reading.
* Organised imports in all classes in an attempt to avoid my brain hurting more.
* Added javadoc comments for the particles enums, I plan to add javadoc comments to all files if they are wanted but I only did a few of the simple and fast ones until it is confirmed that i can add javadocs.
* Added the scr/main/javadoc folder, this will contain package-info files and additional javadoc resources.
* Added javadoc comments to all classes within the me.blackvein.quests.exceptions package.

### CODE REVIEW

**Comment by FlyingPikachu** [comment]
@GregZ123 Wow, thank you for taking the time to do this! Especially the comments <3

I intend to accept this PR once I look over everything later today.

**Comment by GregZ123** [comment]
@FlyingPikachu Seeing as you seem to want javadoc comments I will go through and add them to the rest of the classes. Just as a warning they may not all get written in time for this PR as there are a hell of a lot of classes with no comments.

**Comment by FlyingPikachu** [comment]
@GregZ123 You're more than welcome to, as I'm sure it will encourage our fellow coders to lend a hand, but don't lose sleep over it! I appreciate your work thus far.

**Comment by GregZ123** [comment]
@FlyingPikachu Within the item util the compareItems method currently ignored chat color when comparing the items names, is this meant to be the case?

**Comment by FlyingPikachu** [comment]
@GregZ123 You're referring to this line? https://github.com/FlyingPikachu/Quests/blob/master/src/main/java/me/blackvein/quests/util/ItemUtil.java#L67

I would assume it's intentional. Comparing display name colors would've been easy, so I have to wonder why Blackvein didn't just use `.equals()` or `ItemStack.isSimilar()`

**Comment by GregZ123** [comment]
@FlyingPikachu does the method at https://github.com/FlyingPikachu/Quests/blob/master/src/main/java/me/blackvein/quests/util/MiscUtil.java#L27 need to support ms (milliseconds) or is this not used? If it is not used then this method can be easily simplified with a regex matcher.

**Comment by FlyingPikachu** [comment]
@GregZ123 The only place I see it being used is here https://github.com/FlyingPikachu/Quests/blob/master/src/main/java/me/blackvein/quests/prompts/CreateStagePrompt.java#L4452

Having just checked on v2.8.6, the Delay option in stage creation does still accept "7d 4h 3m 5s" format with a minimum of 1s (no milliseconds). So I can see the point in explaining this format should invalid input be entered, but it's certainly not mandatory. I'll leave the decision of whether to axe or improve the method up to you.

**Comment by FlyingPikachu** [comment]
Planning to accept this PR tomorrow evening :)

**Comment by GregZ123** [comment]
In that case I will try and get the rest of the docs finished for then but I will likely have to make another PR later to finish them off.

**Comment by FlyingPikachu** [comment]
@GregZ123 No rush! If you'd like more time that's fine too, but a separate PR is welcome.

**Comment by GregZ123** [comment]
Sorry that is is taking so long it is just that there is a hell of a lot of undocumented code and I have not had as much time as I had hoped between exams.

**Comment by FlyingPikachu** [comment]
It's really no problem at all! Just don't want any conflicts to develop. In fact, I'm going to accept this now. Focus on your exams lol

**Pull request merged**
